FROM golang:1.16-alpine AS builder

# bash para teste...
RUN apk add --no-cache bash

WORKDIR /src/app
COPY . .

# Using go get.
#RUN go get -d -v

# Compila:
#RUN go build -o /go/bin/app
# Teste... compilando para Linux
RUN GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /go/bin/app
RUN chmod +x /go/bin/app

FROM scratch
# Copia só o executável.
COPY --from=builder /go/bin/app /go/bin/app

ENTRYPOINT ["/go/bin/app"]
